# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: messages.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0emessages.proto\x12\x08messages\"\x1d\n\rCreateRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1b\n\x0b\x46indRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"+\n\x07Project\x12\x12\n\nidentifier\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\"2\n\x0bProjectList\x12#\n\x08projects\x18\x01 \x03(\x0b\x32\x11.messages.Project\"L\n\x12UploadFilesRequest\x12\x10\n\x08\x62ranchId\x18\x01 \x01(\x05\x12$\n\x05\x66iles\x18\x02 \x03(\x0b\x32\x15.messages.FileRequest\"J\n\x11UploadFileRequest\x12\x10\n\x08\x62ranchId\x18\x01 \x01(\x05\x12#\n\x04\x66ile\x18\x02 \x01(\x0b\x32\x15.messages.FileRequest\">\n\x0b\x46ileRequest\x12\x10\n\x08\x66ilePath\x18\x01 \x01(\t\x12\x0c\n\x04hash\x18\x02 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\x0c\"N\n\x13UploadFilesResponse\x12\x10\n\x08\x62ranchId\x18\x01 \x01(\x05\x12%\n\x05\x66iles\x18\x02 \x03(\x0b\x32\x16.messages.FileResponse\"L\n\x12UploadFileResponse\x12\x10\n\x08\x62ranchId\x18\x01 \x01(\x05\x12$\n\x04\x66ile\x18\x02 \x01(\x0b\x32\x16.messages.FileResponse\"]\n\x0c\x46ileResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x10\n\x08\x66ilePath\x18\x02 \x01(\t\x12/\n\x08Versions\x18\x03 \x03(\x0b\x32\x1d.messages.FileVersionResponse\"/\n\x13\x46ileVersionResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04hash\x18\x02 \x01(\t\"Y\n\x15GetFileVersionRequest\x12\x10\n\x08\x62ranchId\x18\x01 \x01(\x05\x12\x0c\n\x02id\x18\x02 \x01(\x05H\x00\x12\x12\n\x08\x66ilePath\x18\x03 \x01(\tH\x00\x42\x0c\n\nfile_oneof\"9\n\x13GetBranchesResponse\x12\"\n\x08\x62ranches\x18\x01 \x03(\x0b\x32\x10.messages.Branch\"R\n\x06\x42ranch\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x1b\n\x0eparentBranchId\x18\x03 \x01(\x05H\x00\x88\x01\x01\x42\x11\n\x0f_parentBranchId\"S\n\x13\x43reateBranchRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x1b\n\x0eparentBranchId\x18\x02 \x01(\x05H\x00\x88\x01\x01\x42\x11\n\x0f_parentBranchIdB\"\xaa\x02\x1fMVCS.Presentation.gRPC.Messagesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'messages_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\252\002\037MVCS.Presentation.gRPC.Messages'
  _globals['_CREATEREQUEST']._serialized_start=28
  _globals['_CREATEREQUEST']._serialized_end=57
  _globals['_FINDREQUEST']._serialized_start=59
  _globals['_FINDREQUEST']._serialized_end=86
  _globals['_PROJECT']._serialized_start=88
  _globals['_PROJECT']._serialized_end=131
  _globals['_PROJECTLIST']._serialized_start=133
  _globals['_PROJECTLIST']._serialized_end=183
  _globals['_UPLOADFILESREQUEST']._serialized_start=185
  _globals['_UPLOADFILESREQUEST']._serialized_end=261
  _globals['_UPLOADFILEREQUEST']._serialized_start=263
  _globals['_UPLOADFILEREQUEST']._serialized_end=337
  _globals['_FILEREQUEST']._serialized_start=339
  _globals['_FILEREQUEST']._serialized_end=401
  _globals['_UPLOADFILESRESPONSE']._serialized_start=403
  _globals['_UPLOADFILESRESPONSE']._serialized_end=481
  _globals['_UPLOADFILERESPONSE']._serialized_start=483
  _globals['_UPLOADFILERESPONSE']._serialized_end=559
  _globals['_FILERESPONSE']._serialized_start=561
  _globals['_FILERESPONSE']._serialized_end=654
  _globals['_FILEVERSIONRESPONSE']._serialized_start=656
  _globals['_FILEVERSIONRESPONSE']._serialized_end=703
  _globals['_GETFILEVERSIONREQUEST']._serialized_start=705
  _globals['_GETFILEVERSIONREQUEST']._serialized_end=794
  _globals['_GETBRANCHESRESPONSE']._serialized_start=796
  _globals['_GETBRANCHESRESPONSE']._serialized_end=853
  _globals['_BRANCH']._serialized_start=855
  _globals['_BRANCH']._serialized_end=937
  _globals['_CREATEBRANCHREQUEST']._serialized_start=939
  _globals['_CREATEBRANCHREQUEST']._serialized_end=1022
# @@protoc_insertion_point(module_scope)
